apiVersion: apps/v1
kind: Deployment
metadata:
  name: migros-project-deployment
  labels:
    app: migros-project
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: migros-project
  template:
    metadata:
      labels:
        app: migros-project
        tier: backend
    spec:
      containers:
      - name: migros-container
        image: migros-project:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
